name: Indice 2014
markdown: redcarpet
pygments: true
# email: prensa@ciudadanointeligente.org
title: Indice de Transparencia Legislativa
# description: "Sitio web de la Fundación Ciudadano Inteligente"
baseurl: "//ciudadanointeligente.github.io/indice"
