markdown: redcarpet
pygments: true
title: Indice de Transparencia Legislativa 2014
description: "El Índice tiene como objetivo sistematizar y analizar información relevante sobre los poderes legislativos y monitorear las tareas que desempeñan desde la perspectiva de la transparencia y el acceso a la información publica desde una perspectiva ciudadana."
baseurl: "//indice2014.transparencialegislativa.org/"
